<a href="https://colab.research.google.com/github/caroSF1/Evaluaci-n/blob/main/Etapa2_EUA_Evaluaci%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Evaluación Etapa 2**
## **Carolina Solis Flores**
## **A01708072**

In [144]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [145]:
df=pd.read_csv("DatosEUA_limpios.csv",encoding='unicode_escape')

**a) host_ acceptance_rate> 50%**

In [146]:
filtro1=df[df['host_acceptance_rate'] > 50]
filtro1

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,958.0,2.020000e+13,1169.0,1.0,1.0,37.770280,-122.433170,3,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",202,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,5858.0,2.020000e+13,8904.0,2.0,2.0,37.744740,-122.420890,4,2.0,...,Entire home/apt,1 bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",235,t,06/03/23,03/05/09,06/08/17,City Registration Pending,f
2,2,8142.0,2.020000e+13,21994.0,13.0,14.0,37.765550,-122.452130,1,1.0,...,Private room,4 shared baths,"[""Security cameras on property"", ""Host greets ...",56,t,06/03/23,08/09/14,27/10/22,City Registration Pending,f
4,4,8739.0,2.020000e+13,7149.0,2.0,2.0,37.760300,-122.421970,3,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",110,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
5,5,142177.0,2.020000e+13,656263.0,1.0,2.0,37.784400,-122.479320,4,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",259,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6929,6929,27790615.3,2.020000e+13,226555948.0,5.3,7.7,37.725231,-122.404776,2,1.0,...,Private room,1 shared bath,"[""Oven"", ""Security cameras on property"", ""Self...",40,t,06/03/23,13/02/23,13/02/23,Exempt,f
6930,6930,27790615.3,2.020000e+13,286802480.0,6.0,10.0,37.753771,-122.399004,1,1.0,...,Private room,1 shared bath,"[""Carbon monoxide alarm"", ""Security cameras on...",56,t,06/03/23,13/02/23,13/02/23,Exempt,t
6931,6931,27790615.3,2.020000e+13,87507815.4,9.0,9.0,37.791994,-122.410000,2,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",164,t,06/03/23,13/02/23,13/02/23,147904,t
6932,6932,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.763060,-122.432023,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.777633,-122.416478,1,1.0,...,Private room,1 shared bath,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",104,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f

In [147]:
#Convertir DataFrame a CSV
filtro1.to_csv("Etapa2_filtroa_EUA.csv")

In [148]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroa_EUA.csv")

**b) sólo los registros con categoría "superhost"**

In [149]:
filtro2=df[df["host_is_superhost"] == "t"]
filtro2

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,958.0,2.020000e+13,1169.0,1.0,1.0,37.770280,-122.433170,3,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",202,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
4,4,8739.0,2.020000e+13,7149.0,2.0,2.0,37.760300,-122.421970,3,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",110,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
7,7,10537.0,2.020000e+13,36752.0,2.0,3.0,37.717500,-122.396980,2,1.0,...,Private room,1.5 shared baths,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",95,t,06/03/23,21/02/10,28/01/23,2022-011003STR,f
8,8,491867.0,2.020000e+13,969518.0,2.0,3.0,37.771960,-122.434770,5,3.0,...,Entire home/apt,2 baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",425,t,06/03/23,14/08/12,19/02/23,STR-0000192,f
9,9,144242.0,2.020000e+13,699215.0,2.0,2.0,37.785460,-122.461480,6,3.0,...,Entire home/apt,2 baths,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",545,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,6913,27790615.3,2.020000e+13,36046172.0,2.0,2.0,37.719700,-122.463300,2,1.0,...,Private room,1 private bath,"[""Security cameras on property"", ""Self check-i...",71,t,06/03/23,09/02/23,13/02/23,1133735,f
6918,6918,27790615.3,2.020000e+13,375566645.0,23.0,26.0,37.767920,-122.424256,1,1.0,...,Private room,1 shared bath,"[""Security cameras on property"", ""Self check-i...",52,t,06/03/23,12/02/23,17/02/23,2023-001339STR,f
6919,6919,27790615.3,2.020000e+13,330231.0,10.0,13.0,37.803929,-122.443176,4,2.0,...,Entire home/apt,2 baths,"[""Oven"", ""Security cameras on property"", ""Cook...",290,t,06/03/23,12/02/23,17/02/23,2023-001339STR,t
6923,6923,27790615.3,2.020000e+13,4452428.0,3.0,3.0,37.784690,-122.392874,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",110,t,06/03/23,10/02/23,10/02/23,2023-000835STR,f
6929,6929,27790615.3,2.020000e+13,226555948.0,5.3,7.7,37.725231,-122.404776,2,1.0,...,Private room,1 shared bath,"[""Oven"", ""Security cameras on property"", ""Self...",40,t,06/03/23,13/02/23,13/02/23,Exempt,f

In [150]:
#Convertir DataFrame a CSV
filtro2.to_csv("Etapa2_filtrob_EUA.csv")

In [151]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrob_EUA.csv")

c) Los registros que no hallan verificado identidad " not identity_verified"

In [152]:
filtro3 = df[df["host_identity_verified"] == "f"]
filtro3

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
6,6,490931.0,2.020000e+13,1269188.0,1.0,3.0,37.747660,-122.420410,2,1.0,...,Private room,1 bath,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",100,t,06/03/23,22/04/14,26/11/22,STR-0002192,f
28,28,18231.0,2.020000e+13,70224.0,1.0,1.0,37.749160,-122.429710,3,1.6,...,Entire home/apt,1 bath,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",95,t,06/03/23,05/06/10,19/06/22,1025574,f
38,38,193292.0,2.020000e+13,937281.0,1.0,1.0,37.751170,-122.425670,1,1.0,...,Private room,Half-bath,"[""Carbon monoxide alarm"", ""First aid kit"", ""Sm...",120,t,06/03/23,06/12/11,22/09/14,STR-0000017,f
39,39,201313.0,2.020000e+13,984585.0,1.0,1.0,37.803560,-122.404370,2,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",175,t,06/03/23,17/05/18,26/06/21,STR-0000017,f
71,71,231129.0,2.020000e+13,1208533.0,5.0,6.0,37.792780,-122.410070,3,1.0,...,Entire home/apt,1 bath,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",1000,t,06/03/23,20/01/12,23/10/22,City Registration Pending,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6885,6885,27790615.3,2.020000e+13,157999191.0,24.0,24.0,37.800850,-122.433658,1,1.0,...,Private room,1 shared bath,"[""Carbon monoxide alarm"", ""Lock on bedroom doo...",75,t,06/03/23,27/02/23,27/02/23,2023-001260STR,f
6905,6905,27790615.3,2.020000e+13,240202942.0,2.0,4.0,37.731587,-122.400000,2,1.0,...,Entire home/apt,1 bath,"[""Contact host body soap"", ""Security cameras o...",76,t,06/03/23,05/02/23,28/02/23,2022-013018STR,t
6931,6931,27790615.3,2.020000e+13,87507815.4,9.0,9.0,37.791994,-122.410000,2,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",164,t,06/03/23,13/02/23,13/02/23,147904,t
6932,6932,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.763060,-122.432023,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.777633,-122.416478,1,1.0,...,Private room,1 shared bath,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",104,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f

In [153]:
#Convertir DataFrame a CSV
filtro3.to_csv("Etapa2_filtroc_EUA.csv")

In [154]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroc_EUA.csv")

d) Los registro cuyo property_type = "Private room" y "Hotel room"

In [155]:
filtro4 = df[(df["property_type"] == 'Private room') | (df["property_type"] == "Hotel room")]
filtro4

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
7,7,10537.0,2.020000e+13,36752.0,2.0,3.0,37.71750,-122.39698,2,1.0,...,Private room,1.5 shared baths,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",95,t,06/03/23,21/02/10,28/01/23,2022-011003STR,f
1575,1575,14305759.0,2.020000e+13,29483318.0,3.0,3.0,37.75145,-122.40719,2,1.0,...,Private room,1 shared bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",69,t,06/03/23,11/08/16,01/11/20,City registration pending,t
2049,2049,20957462.0,2.020000e+13,150732464.0,7.0,9.0,37.79586,-122.41915,2,1.6,...,Private room,1 private bath,"[""Free street parking"", ""Dishes and silverware...",60,t,06/03/23,09/12/17,17/01/23,STR-0002234,t
4014,4014,43477461.0,2.020000e+13,150732464.0,7.0,9.0,37.79525,-122.41931,1,1.6,...,Private room,1 bath,"[""Essentials"", ""Dishes and silverware"", ""Coffe...",56,t,06/03/23,28/02/22,09/12/22,STR-0004224,f

In [156]:
#Convertir DataFrame a CSV
filtro4.to_csv("Etapa2_filtrod_EUA.csv")

In [157]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrod_EUA.csv")

e) Los registros que cuenten con bathroom > 1

In [158]:
filtro5= df[~(df["bathrooms_text"] == '1 bath')  & ~(df["bathrooms_text"] == "1 private bath")]
filtro5

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,2,8142.0,2.020000e+13,21994.0,13.0,14.0,37.765550,-122.452130,1,1.0,...,Private room,4 shared baths,"[""Security cameras on property"", ""Host greets ...",56,t,06/03/23,08/09/14,27/10/22,City Registration Pending,f
3,3,8339.0,2.020000e+13,24215.0,2.0,6.0,37.775640,-122.436420,4,2.0,...,Entire home/apt,1.5 baths,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",575,t,06/03/23,25/09/09,28/06/19,STR-0000264,f
7,7,10537.0,2.020000e+13,36752.0,2.0,3.0,37.717500,-122.396980,2,1.0,...,Private room,1.5 shared baths,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",95,t,06/03/23,21/02/10,28/01/23,2022-011003STR,f
8,8,491867.0,2.020000e+13,969518.0,2.0,3.0,37.771960,-122.434770,5,3.0,...,Entire home/apt,2 baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",425,t,06/03/23,14/08/12,19/02/23,STR-0000192,f
9,9,144242.0,2.020000e+13,699215.0,2.0,2.0,37.785460,-122.461480,6,3.0,...,Entire home/apt,2 baths,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",545,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6926,6926,27790615.3,2.020000e+13,222540569.0,7.0,8.0,37.716070,-122.391170,2,1.0,...,Private room,1.5 shared baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",83,t,06/03/23,03/02/23,25/02/23,2022-012006STR,f
6929,6929,27790615.3,2.020000e+13,226555948.0,5.3,7.7,37.725231,-122.404776,2,1.0,...,Private room,1 shared bath,"[""Oven"", ""Security cameras on property"", ""Self...",40,t,06/03/23,13/02/23,13/02/23,Exempt,f
6930,6930,27790615.3,2.020000e+13,286802480.0,6.0,10.0,37.753771,-122.399004,1,1.0,...,Private room,1 shared bath,"[""Carbon monoxide alarm"", ""Security cameras on...",56,t,06/03/23,13/02/23,13/02/23,Exempt,t
6933,6933,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.777633,-122.416478,1,1.0,...,Private room,1 shared bath,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",104,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6934,6934,27790615.3,2.020000e+13,87507815.4,3.0,4.0,37.738325,-122.396603,2,1.0,...,Private room,1 shared bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",65,t,06/03/23,03/03/23,03/03/23,2022-012562STR,f

In [159]:
#Convertir DataFrame a CSV
filtro5.to_csv("Etapa2_filtroe.csv")

In [160]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroe.csv")

f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo "Entire home"

In [161]:
filtro6 = df[(df["price"] > 10000) & (df["room_type"] == "Entire home/apt")]
filtro6

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
5759,5759,27790615.3,2.020000e+13,32878131.0,3.0,6.0,37.732590,-122.43337,4,1.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Security cameras on...",14000,t,06/03/23,24/08/22,15/11/22,STR-0001378,f
6490,6490,27790615.3,2.020000e+13,91333416.0,32.0,50.0,37.781091,-122.47233,4,2.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Hangers"", ""Iron"", ""...",25000,t,06/03/23,03/02/23,03/02/23,2022-004730STR,t

In [162]:
#Convertir DataFrame a CSV
filtro6.to_csv("Etapa2_filtrof_EUA.csv")

In [163]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrof_EUA.csv")

g) Los registros cuyo review_scores_cleanliness > 4.5

In [164]:
filtro7 = df[df['review_scores_cleanliness'] > 4.5]
filtro7

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,958.0,2.020000e+13,1169.0,1.0,1.0,37.770280,-122.433170,3,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",202,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
1,1,5858.0,2.020000e+13,8904.0,2.0,2.0,37.744740,-122.420890,4,2.0,...,Entire home/apt,1 bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",235,t,06/03/23,03/05/09,06/08/17,City Registration Pending,f
2,2,8142.0,2.020000e+13,21994.0,13.0,14.0,37.765550,-122.452130,1,1.0,...,Private room,4 shared baths,"[""Security cameras on property"", ""Host greets ...",56,t,06/03/23,08/09/14,27/10/22,City Registration Pending,f
3,3,8339.0,2.020000e+13,24215.0,2.0,6.0,37.775640,-122.436420,4,2.0,...,Entire home/apt,1.5 baths,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",575,t,06/03/23,25/09/09,28/06/19,STR-0000264,f
4,4,8739.0,2.020000e+13,7149.0,2.0,2.0,37.760300,-122.421970,3,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",110,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,6931,27790615.3,2.020000e+13,87507815.4,9.0,9.0,37.791994,-122.410000,2,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",164,t,06/03/23,13/02/23,13/02/23,147904,t
6932,6932,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.763060,-122.432023,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.777633,-122.416478,1,1.0,...,Private room,1 shared bath,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",104,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6934,6934,27790615.3,2.020000e+13,87507815.4,3.0,4.0,37.738325,-122.396603,2,1.0,...,Private room,1 shared bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",65,t,06/03/23,03/03/23,03/03/23,2022-012562STR,f
6935,6935,27790615.3,2.020000e+13,4836128.0,2.0,4.0,37.786442,-122.457006,2,1.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Security cameras on...",375,t,06/03/23,03/03/23,03/03/23,2022-012562STR,t

In [165]:
#Convertir DataFrame a CSV
filtro7.to_csv("Etapa2_filtrog_EUA.csv")

In [166]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrog_EUA.csv")

h) Los registros cuyo review_scores_value > 4.9

In [167]:
filtro8 = df[df['review_scores_value'] > 4.9]
filtro8

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
9,9,144242.0,2.020000e+13,699215.0,2.0,2.0,37.785460,-122.461480,6,3.0,...,Entire home/apt,2 baths,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",545,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
24,24,149108.0,2.020000e+13,719538.0,2.0,2.0,37.762160,-122.450220,2,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Security cameras on property"", ""Cook...",180,t,06/03/23,01/08/14,14/02/23,STR-0000672,f
26,26,12522.0,2.020000e+13,18431.0,1.0,2.0,37.762370,-122.429920,2,1.0,...,Private room,1.5 shared baths,"[""Essentials"", ""Bed linens"", ""Dishes and silve...",99,t,06/03/23,14/01/10,20/02/23,STR-0000057,f
46,46,530857.0,2.020000e+13,2607120.0,2.0,3.0,37.717270,-122.436440,1,1.0,...,Private room,1.5 shared baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""S...",85,t,06/03/23,20/05/18,31/01/23,STR-0003035,t
53,53,561602.0,2.020000e+13,2760904.0,1.0,1.0,37.744030,-122.417550,2,2.0,...,Private room,1 shared bath,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",80,t,06/03/23,23/07/12,01/03/23,STR-0001006,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6920,6920,27790615.3,2.020000e+13,407298390.0,9.0,12.0,37.801789,-122.426501,2,1.0,...,Private room,1 private bath,"[""Security cameras on property"", ""Self check-i...",107,t,06/03/23,10/02/23,10/02/23,Exempt,t
6924,6924,27790615.3,2.020000e+13,222540569.0,7.0,8.0,37.716079,-122.390953,2,1.0,...,Private room,1.5 shared baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",79,t,06/03/23,07/02/23,07/02/23,2022-012006STR,f
6925,6925,27790615.3,2.020000e+13,222540569.0,7.0,8.0,37.716214,-122.391460,2,1.0,...,Private room,1.5 shared baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",85,t,06/03/23,10/02/23,24/02/23,2022-012006STR,f
6927,6927,27790615.3,2.020000e+13,87507815.4,32.0,38.0,37.788619,-122.422556,2,1.0,...,Private room,1 private bath,"[""Security cameras on property"", ""Self check-i...",80,t,06/03/23,13/02/23,13/02/23,Exempt,f
6932,6932,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.763060,-122.432023,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f

In [168]:
#Convertir DataFrame a CSV
filtro8.to_csv("Etapa2_filtroh_EUA.csv")

In [169]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroh_EUA.csv")

i) Los registros cuya availability_365<100

In [170]:
filtro9=df[df['availability_365'] < 100]
filtro9

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
5,5,142177.0,2.020000e+13,656263.0,1.0,2.0,37.784400,-122.479320,4,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",259,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
8,8,491867.0,2.020000e+13,969518.0,2.0,3.0,37.771960,-122.434770,5,3.0,...,Entire home/apt,2 baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",425,t,06/03/23,14/08/12,19/02/23,STR-0000192,f
9,9,144242.0,2.020000e+13,699215.0,2.0,2.0,37.785460,-122.461480,6,3.0,...,Entire home/apt,2 baths,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",545,t,06/03/23,05/07/11,02/01/22,2022-011317STR,f
11,11,144978.0,2.020000e+13,216682.0,9.0,9.0,37.792330,-122.424310,1,1.0,...,Private room,1 bath,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",55,t,06/03/23,10/07/11,28/02/23,2022-011317STR,f
15,15,501770.0,2.020000e+13,2475480.0,5.0,5.0,37.772520,-122.438460,2,1.0,...,Entire home/apt,1 bath,"[""TV with standard cable, DVD player, HBO Max""...",220,t,06/03/23,27/06/12,26/09/22,STR-0005156,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,6913,27790615.3,2.020000e+13,36046172.0,2.0,2.0,37.719700,-122.463300,2,1.0,...,Private room,1 private bath,"[""Security cameras on property"", ""Self check-i...",71,t,06/03/23,09/02/23,13/02/23,1133735,f
6917,6917,27790615.3,2.020000e+13,45555637.0,1.0,2.0,37.748247,-122.433441,2,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Security cameras on property"", ""Self...",222,t,06/03/23,12/02/23,17/02/23,2023-001339STR,f
6918,6918,27790615.3,2.020000e+13,375566645.0,23.0,26.0,37.767920,-122.424256,1,1.0,...,Private room,1 shared bath,"[""Security cameras on property"", ""Self check-i...",52,t,06/03/23,12/02/23,17/02/23,2023-001339STR,f
6923,6923,27790615.3,2.020000e+13,4452428.0,3.0,3.0,37.784690,-122.392874,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",110,t,06/03/23,10/02/23,10/02/23,2023-000835STR,f
6931,6931,27790615.3,2.020000e+13,87507815.4,9.0,9.0,37.791994,-122.410000,2,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",164,t,06/03/23,13/02/23,13/02/23,147904,t

In [171]:
#Convertir DataFrame a CSV
filtro9.to_csv("Etapa2_filtroi_EUA.csv")

In [172]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroi_EUA.csv")

j) Los registros cuya host_ response_time sea "within an hour"

In [173]:
filtro10 = df[df["host_response_time"] == "within an hour"]
filtro10

,Unnamed: 0,Ã¯Â»Â¿id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,958.0,2.020000e+13,1169.0,1.0,1.0,37.770280,-122.433170,3,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",202,t,06/03/23,23/07/09,19/02/23,City Registration Pending,f
2,2,8142.0,2.020000e+13,21994.0,13.0,14.0,37.765550,-122.452130,1,1.0,...,Private room,4 shared baths,"[""Security cameras on property"", ""Host greets ...",56,t,06/03/23,08/09/14,27/10/22,City Registration Pending,f
4,4,8739.0,2.020000e+13,7149.0,2.0,2.0,37.760300,-122.421970,3,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",110,t,06/03/23,01/08/09,25/02/23,STR-0000028,f
5,5,142177.0,2.020000e+13,656263.0,1.0,2.0,37.784400,-122.479320,4,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",259,t,06/03/23,21/10/11,17/02/23,STR-0002192,f
12,12,493889.0,2.020000e+13,2439917.0,2.0,3.0,37.728330,-122.441250,2,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",235,t,06/03/23,17/06/12,25/10/22,STR-0004820,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,6931,27790615.3,2.020000e+13,87507815.4,9.0,9.0,37.791994,-122.410000,2,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",164,t,06/03/23,13/02/23,13/02/23,147904,t
6932,6932,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.763060,-122.432023,2,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6933,6933,27790615.3,2.020000e+13,87507815.4,1.0,1.0,37.777633,-122.416478,1,1.0,...,Private room,1 shared bath,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",104,t,06/03/23,03/03/23,03/03/23,2023-001477STR,f
6934,6934,27790615.3,2.020000e+13,87507815.4,3.0,4.0,37.738325,-122.396603,2,1.0,...,Private room,1 shared bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",65,t,06/03/23,03/03/23,03/03/23,2022-012562STR,f
6935,6935,27790615.3,2.020000e+13,4836128.0,2.0,4.0,37.786442,-122.457006,2,1.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Security cameras on...",375,t,06/03/23,03/03/23,03/03/23,2022-012562STR,t

In [174]:
#Convertir DataFrame a CSV
filtro10.to_csv("Etapa2_filtroj_EUA.csv")

In [175]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroj_EUA.csv")