<a href="https://colab.research.google.com/github/caroSF1/Evaluaci-n/blob/main/Evaluaci%C3%B3n_M%C3%A9xico_Etapa2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Evaluación Etapa 2* México*
## **Carolina Solis Flores**
## **A01708072**

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [46]:
df=pd.read_csv("DatosMéxico_limpios.csv", low_memory=False)

**a) host_ acceptance_rate> 50%**

In [47]:
filtro1=df[df['host_acceptance_rate'] > 50]
filtro1

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
1,1.0,2072354,2.02303E+13,16840050,3,3,19.35358,-99.16948,2,1,...,Entire guest suite,Entire home/apt,1 bath,"[""Free street parking"", ""Cleaning products"", ""...",830.0,t,30/03/23,01/01/14,04/11/22,f
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
3,3.0,35797,2.02303E+13,153786,1,1,19.38283,-99.2,2,1,...,Entire villa,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24221,24219.0,8.53924E+17,2.02303E+13,488030249,3,4,19.39666335,-99.14814491,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",760.0,t,30/03/23,29/03/23,29/03/23,f
24222,24220.0,8.53967E+17,2.02303E+13,506816029,1,1,19.39202345,-99.11872158,7,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Lake access"", ""Ski-in/Ski-out"", ""Wifi"", ""Out...",1520.0,t,29/03/23,29/03/23,29/03/23,t
24223,24221.0,8.54225E+17,2.02303E+13,154670560,1,6,19.3710885,-99.1901864,2,2,...,Private room in home,Private room,2.5 shared baths,"[""Luggage dropoff allowed"", ""Shared patio or b...",533.0,t,29/03/23,29/03/23,29/03/23,f
24224,24222.0,8.54248E+17,2.02303E+13,7799414,13,13,19.4037919,-99.1649783,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Condit...",1200.0,t,30/03/23,29/03/23,29/03/23,t
24225,24223.0,8.5426E+17,2.02303E+13,506864314,2,2,19.42628282,-99.17560335,6,3,...,Entire rental unit,Entire home/apt,1 bath,"[""Long term stays allowed"", ""Cleaning products...",1720.0,t,30/03/23,29/03/23,29/03/23,t

In [48]:
#Convertir DataFrame a CSV
filtro1.to_csv("Etapa2_filtroa_México.csv")

In [13]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroa_México.csv")

**b) sólo los registros con categoría "superhost"**

In [49]:
filtro2=df[df["host_is_superhost"] == "t"]
filtro2

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
6,6.0,56074,2.02303E+13,265650,2,6,19.43977,-99.15605,2,1,...,Entire condo,Entire home/apt,1 bath,"[""Luggage dropoff allowed"", ""Long term stays a...",650.0,t,29/03/23,02/04/11,21/01/23,f
7,7.0,61792,2.02303E+13,299558,2,3,19.41083,-99.18057,2,1,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,30/03/23,01/11/17,31/12/22,f
8,8.0,704779,2.02303E+13,2872228,13,14,19.43103,-99.14661,2,1,...,Entire condo,Entire home/apt,1 bath,"[""Ethernet connection"", ""TV with standard cabl...",943.0,t,29/03/23,21/08/13,27/02/23,f
9,9.0,728372,2.02303E+13,3777702,6,7,19.44222,-99.14461,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""TV with standard cabl...",2561.0,t,29/03/23,31/10/12,17/02/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24173,24171.0,8.55775E+17,2.02303E+13,333035396,5.3,6.2,19.38039756,-99.18698569,6,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Smoke alarm"", ""Single level home"", ""Long ter...",1226.0,t,30/03/23,26/03/23,26/03/23,t
24181,24179.0,8.56003E+17,2.02303E+13,10764020,5.3,6.2,19.43299385,-99.19632715,2,1,...,Entire serviced apartment,Entire home/apt,1 bath,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...",2382.0,t,30/03/23,26/03/23,26/03/23,f
24193,24191.0,8.56174E+17,2.02303E+13,420886866,2,2,19.4466065,-99.15751621,4,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Kitchen"", ""TV"", ""Carb...",750.0,t,30/03/23,29/03/23,29/03/23,f
24205,24203.0,8.565E+17,2.02303E+13,8905097,5.3,6.2,19.36003801,-99.2,4,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Pets allowed"", ""Self ...",2179.0,t,30/03/23,29/03/23,29/03/23,t
24224,24222.0,8.54248E+17,2.02303E+13,7799414,13,13,19.4037919,-99.1649783,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Condit...",1200.0,t,30/03/23,29/03/23,29/03/23,t

In [15]:
#Convertir DataFrame a CSV
filtro2.to_csv("Etapa2_filtrob_México.csv")

In [16]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrob_México.csv")

c) Los registros que no hallan verificado identidad " not identity_verified"

In [50]:
filtro3 = df[df["host_identity_verified"] == "f"]
filtro3

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
21,21.0,131610,2.02303E+13,647454,3,4,19.35416,-99.16488,2,1,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,29/03/23,06/09/14,29/01/23,f
61,61.0,276504,2.02303E+13,1444589,1,1,19.38061,-99.12729,2,1.6,...,Entire rental unit,Entire home/apt,1 bath,"[""Elevator"", ""Wifi"", ""Washer"", ""Kitchen"", ""Poo...",1815.0,f,30/03/23,01/01/12,25/01/21,f
68,68.0,291804,2.02303E+13,1511568,1,1,19.36305,-99.15412,1,1,...,Private room in rental unit,Private room,1 bath,"[""Kitchen"", ""Smoking allowed"", ""Dryer"", ""Washer""]",545.0,t,30/03/23,12/08/13,13/03/23,f
70,70.0,298873,2.02303E+13,1539548,1,3,19.43358,-99.14452,4,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Elevator"", ""Wifi"", ""Oven"", ""Iron"", ""Washer"",...",1362.0,t,30/03/23,19/04/12,03/11/19,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23697,23695.0,8.41965E+17,2.02303E+13,13667851,2,2,19.4,-99.2,1,1,...,Private room in home,Private room,1.5 shared baths,"[""Wifi"", ""Kitchen"", ""Lock on bedroom door"", ""H...",240.0,t,29/03/23,20/03/23,27/03/23,f
23875,23873.0,8.48589E+17,2.02303E+13,487627497,17,19,19.42332394,-99.16096109,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...",1362.0,t,30/03/23,26/03/23,26/03/23,t
23967,23965.0,8.49311E+17,2.02303E+13,408076348,3,3,19.4209212,-99.1560909,2,1,...,Private room in bed and breakfast,Private room,1 private bath,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...",5200.0,f,30/03/23,25/03/23,25/03/23,f
23968,23966.0,8.49316E+17,2.02303E+13,408076348,3,3,19.42096,-99.15738,2,1,...,Private room in bed and breakfast,Private room,1 private bath,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...",5200.0,f,30/03/23,25/03/23,25/03/23,f
23974,23972.0,8.49319E+17,2.02303E+13,408076348,3,3,19.42085033,-99.15724236,2,1,...,Private room in bed and breakfast,Private room,1 private bath,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...",6800.0,f,30/03/23,20/03/23,20/03/23,f

In [18]:
#Convertir DataFrame a CSV
filtro3.to_csv("Etapa2_filtroc_México.csv")

In [19]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroc_México.csv")

d) Los registro cuyo property_type = "Private room" y "Hotel room"

In [51]:
filtro4 = df[(df["property_type"] == 'Private room') | (df["property_type"] == "Hotel room")]
filtro4

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
21,21.0,131610,2.02303E+13,647454,3,4,19.35416,-99.16488,2,1,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,29/03/23,06/09/14,29/01/23,f
1062,1062.0,12271259,2.02303E+13,2556582,1,1,19.39057309,-99.12979776,2,1,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",748.0,t,29/03/23,23/05/17,21/11/22,f
2670,2670.0,19639981,2.02303E+13,136125882,1,2,19.34166,-99.15035,1,1,...,Private room,Private room,1 shared bath,"[""Wifi"", ""Breakfast"", ""Washer"", ""Smoking allow...",181.0,t,29/03/23,26/02/23,26/02/23,t
2805,2805.0,20089283,2.02303E+13,142841816,1,1,19.4,-99.2,2,1,...,Private room,Private room,2 shared baths,"[""Elevator"", ""Extra pillows and blankets"", ""Et...",400.0,t,29/03/23,10/08/17,07/03/23,t
3065,3065.0,21067896,2.02303E+13,151816281,2,2,19.45733,-99.21227,2,1,...,Private room,Private room,1 shared bath,"[""Smoke alarm"", ""Shared gym nearby"", ""Luggage ...",600.0,t,30/03/23,12/12/17,13/01/23,f
3257,3257.0,21765818,2.02303E+13,158580118,1,1,19.43487,-99.18768,2,1,...,Private room,Private room,1 private bath,"[""Private entrance"", ""Wifi"", ""Washer"", ""Hanger...",508.0,t,30/03/23,03/12/17,19/03/23,t
3359,3359.0,22230184,2.02303E+13,93911392,28,6.2,19.41364,-99.16292,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Single...",765.0,t,30/03/23,23/12/17,25/03/23,f
3372,3372.0,22247072,2.02303E+13,93911392,28,6.2,19.41538,-99.16064,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""HDTV w...",822.0,t,30/03/23,21/12/17,19/03/23,f
3455,3455.0,22340146,2.02303E+13,115584349,3,3,19.433,-99.14101,2,1,...,Private room,Private room,1 shared bath,"[""Wifi"", ""Luggage dropoff allowed"", ""Dishes an...",375.0,t,30/03/23,02/01/18,27/11/21,f
3571,3571.0,23026367,2.02303E+13,170856978,1,2,19.4369,-99.20763,2,1.6,...,Private room,Private room,1 private bath,"[""Elevator"", ""Smoke alarm"", ""Private entrance""...",1000.0,t,30/03/23,11/02/18,27/03/23,t
3605,3605.0,23100799,2.02303E+13,103716258,1,1,19.43409,-99.13191,2.9,3,...,Private room,Private room,6 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",27435.0,t,29/03/23,23/03/19,31/10/22,t
4303,4303.0,25868032,2.02303E+13,34171966,3,4,19.34903,-99.16493,2,1,...,Private room,Private room,1 private bath,"[""Wifi"", ""Cooking basics"", ""Iron"", ""Washer"", ""...",526.0,t,30/03/23,02/07/18,27/03/23,t
5667,5667.0,31826983,2.02303E+13,185535296,7,10,19.33975,-99.20108,1,1.6,...,Private room,Private room,1 private bath,"[""Wifi"", ""Hangers"", ""Essentials""]",579.0,t,29/03/23,25/02/19,20/05/22,t
6244,6244.0,33051319,2.02303E+13,245350245,4,8,19.44535,-99.2,2.9,1,...,Private room,Private room,1 private bath,"[""Luggage dropoff allowed"", ""Long term stays a...",1757.0,t,29/03/23,24/03/19,27/11/22,t
11129,11127.0,47007658,2.02303E+13,345395010,2,5,19.40288,-99.13481,2,1,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Private entrance"", ""W...",320.0,t,30/03/23,29/06/21,27/02/23,t
11921,11919.0,49045093,2.02303E+13,133609729,2,2,19.37162,-99.16179,1,1,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Hot water"", ""Essenti...",450.0,t,30/03/23,01/05/22,20/11/22,f
12300,12298.0,50106680,2.02303E+13,290843938,4,5,19.39061,-99.18114,2,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Smoke alarm"", ""Hot wa...",339.0,t,29/03/23,05/12/21,23/03/23,f
12713,12711.0,50796337,2.02303E+13,2518152,8,8,19.45877,-99.17539,2,1,...,Private room,Private room,1.5 shared baths,"[""Free street parking"", ""BBQ grill"", ""Luggage ...",750.0,t,29/03/23,20/01/22,20/01/22,t
12842,12840.0,50893960,2.02303E+13,411507264,1,1,19.453215,-99.181328,1,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Private outdoor kitchen"", ""Ho...",1081.0,t,29/03/23,08/11/21,24/02/23,t
12865,12863.0,51164390,2.02303E+13,161016544,2,2,19.41581,-99.16108,1,1,...,Private room,Private room,3.5 shared baths,"[""City skyline view"", ""Long term stays allowed...",364.0,t,30/03/23,06/08/21,25/01/23,t
13675,13673.0,52557368,2.02303E+13,93911392,28,6.2,19.41534,-99.16228,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",640.0,t,30/03/23,17/10/21,12/03/23,f
13676,13674.0,52557770,2.02303E+13,93911392,28,6.2,19.41334,-99.16086,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",733.0,t,30/03/23,15/10/21,26/03/23,f
13682,13680.0,52558024,2.02303E+13,93911392,28,6.2,19.41389,-99.1629,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",712.0,t,30/03/23,14/10/21,19/03/23,f
13715,13713.0,52536577,2.02303E+13,93911392,28,6.2,19.41382,-99.1627,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",739.0,t,30/03/23,14/10/21,28/02/23,f
14806,14804.0,53805586,2.02303E+13,248524358,6,6,19.38331,-99.16172,1,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Free street parking"",...",514.0,t,30/03/23,31/08/22,31/08/22,f
14920,14918.0,54106290,2.02303E+13,438593737,4,4,19.3548,-99.16817,2,1,...,Private room,Private room,1 private bath,"[""Wifi"", ""Shower gel"", ""Cleaning available dur...",1491.0,t,30/03/23,12/01/22,26/06/22,t
15032,15030.0,54194769,2.02303E+13,282436180,2,2,19.45267,-99.2,1,3,...,Private room,Private room,1 shared bath,"[""BBQ grill"", ""HDTV with Netflix"", ""Cleaning p...",400.0,t,29/03/23,07/08/22,30/12/22,f
15094,15092.0,54215774,2.02303E+13,439419001,2,2,19.37657,-99.16506,1,1,...,Private room,Private room,1.5 baths,"[""Stainless steel oven"", ""Free street parking""...",450.0,t,30/03/23,04/02/22,03/05/22,f
15359,15357.0,5.53083E+17,2.02303E+13,438593737,4,4,19.3563,-99.16654,2,1,...,Private room,Private room,1 private bath,"[""Wifi"", ""Shower gel"", ""Free street parking"", ...",1491.0,t,30/03/23,10/02/22,13/11/22,t
16018,16016.0,5.88691E+17,2.02303E+13,400461338,4,18,19.37866,-99.16659,2,1,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Luggage dropoff allow...",771.0,t,30/03/23,26/03/22,01/01/23,f
16936,16934.0,6.26031E+17,2.02303E+13,66387078,5.3,32,19.430712,-99.163963,1,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",243.0,t,29/03/23,23/05/22,10/03/23,t
16937,16935.0,6.26044E+17,2.02303E+13,66387078,5.3,32,19.43176,-99.16445,1,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",234.0,t,29/03/23,31/05/22,27/02/23,t
17156,17154.0,6.38322E+17,2.02303E+13,283357024,2,3,19.42988014,-99.15309143,2,1,...,Private room,Private room,1 private bath,"[""Laguna Cyprien shampoo"", ""Luggage dropoff al...",3000.0,t,30/03/23,26/06/22,21/03/23,f
17253,17251.0,6.4566E+17,2.02303E+13,463433619,3,4,19.41896,-99.15701,2,1,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Smoke alarm"", ""Hot wa...",1800.0,t,30/03/23,18/07/22,18/07/22,f
18956,18954.0,7.01263E+17,2.02303E+13,248524358,6,6,19.38437481,-99.16057594,1,1,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Hot water kettle"", ""L...",900.0,t,30/03/23,15/12/22,15/12/22,f
19585,19583.0,7.28639E+17,2.02303E+13,49926105,3,3,19.35469,-99.14286,3,1,...,Private room,Private room,Private half-bath,"[""Free street parking"", ""BBQ grill"", ""Luggage ...",1486.0,t,29/03/23,23/11/22,26/03/23,f
19759,19757.0,7.33272E+17,2.02303E+13,972988,3,8,19.44418,-99.16079,2,1,...,Private room,Private room,1.5 shared baths,"[""Wifi"", ""Patio or balcony"", ""Washer"", ""City s...",600.0,t,30/03/23,02/11/22,21/03/23,t
19922,19920.0,7.41534E+17,2.02303E+13,450807747,1,1,19.38386,-99.17638,2,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",402.0,t,29/03/23,23/10/22,04/02/23,f
20378,20376.0,7.5745E+17,2.02303E+13,438549721,4,7,19.38061969,-99.19304777,1,1,...,Private room,Private room,1 shared bath,"[""Stainless steel oven"", ""Luggage dropoff allo...",220.0,t,30/03/23,06/12/22,07/01/23,t
20858,20856.0,7.66892E+17,2.02303E+13,488289168,2,3,19.42993,-99.16546,2,1,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Security cameras on ...",450.0,t,30/03/23,17/12/22,23/03/23,t
20860,20858.0,7.68987E+17,2.02303E+13,212991892,4,18,19.37823,-99.16797,2,1,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Luggage dropoff allow...",600.0,t,30/03/23,25/02/23,14/03/23,t
20866,20864.0,7.66896E+17,2.02303E+13,488289168,2,3,19.4294769,-99.1665583,2,1,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Security cameras on ...",500.0,t,30/03/23,28/01/23,19/02/23,t
22717,22715.0,8.21225E+17,2.02303E+13,248524358,6,6,19.38538852,-99.15999246,2,1,...,Private room,Private room,1 bath,"[""Ethernet connection"", ""Free street parking"",...",529.0,t,30/03/23,12/02/23,04/03/23,t

In [21]:
#Convertir DataFrame a CSV
filtro4.to_csv("Etapa2_filtrod_México.csv")

In [22]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrod_México.csv")

e) Los registros que cuenten con bathroom > 1

In [52]:
filtro5= df[~(df["bathrooms_text"] == '1 bath')  & ~(df["bathrooms_text"] == "1 private bath")]
filtro5

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
5,5.0,2075738,2.02303E+13,2339771,1,2,19.41909,-99.16043,2,1,...,Entire loft,Entire home/apt,2 baths,"[""BBQ grill"", ""Luggage dropoff allowed"", ""TV w...",2561.0,t,29/03/23,05/02/14,27/02/23,f
7,7.0,61792,2.02303E+13,299558,2,3,19.41083,-99.18057,2,1,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,30/03/23,01/11/17,31/12/22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24208,24206.0,8.56513E+17,2.02303E+13,445250346,4,4,19.4196508,-99.16457,6,3,...,Entire home,Entire home/apt,2 baths,"[""Stainless steel oven"", ""Ethernet connection""...",3240.0,t,30/03/23,29/03/23,29/03/23,t
24212,24210.0,8.53691E+17,2.02303E+13,155903047,1,1,19.4345759,-99.1732162,4,2,...,Entire rental unit,Entire home/apt,2.5 baths,"[""Wifi"", ""Fire extinguisher"", ""Kitchen"", ""TV"",...",1741.0,t,30/03/23,29/03/23,29/03/23,t
24215,24213.0,8.53708E+17,2.02303E+13,506768013,1,1,19.43362825,-99.1819019,2,2,...,Private room in rental unit,Private room,1 shared bath,"[""Wifi"", ""Patio or balcony"", ""Washer"", ""Refrig...",750.0,t,30/03/23,29/03/23,29/03/23,f
24220,24218.0,8.53922E+17,2.02303E+13,506810572,4,4,19.38511677,-99.11769287,2,1,...,Private room in home,Private room,1 shared bath,"[""Wifi"", ""Washer"", ""Pets allowed"", ""Outdoor sh...",251.0,t,29/03/23,29/03/23,29/03/23,t
24223,24221.0,8.54225E+17,2.02303E+13,154670560,1,6,19.3710885,-99.1901864,2,2,...,Private room in home,Private room,2.5 shared baths,"[""Luggage dropoff allowed"", ""Shared patio or b...",533.0,t,29/03/23,29/03/23,29/03/23,f

In [24]:
#Convertir DataFrame a CSV
filtro5.to_csv("Etapa2_filtroe_México.csv")

In [25]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroe_México.csv")

f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo "Entire home"

In [53]:
filtro6 = df[(df["price"] > 10000) & (df["room_type"] == "Entire home/apt")]
filtro6

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
37,37.0,187030,2.02303E+13,899360,6,8,19.41057,-99.1773,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",50000.0,t,30/03/23,01/11/11,15/03/23,f
418,418.0,6041044,2.02303E+13,7529413,1,1,19.42898,-99.16885,6,3,...,Entire townhouse,Entire home/apt,5.5 baths,"[""Ethernet connection"", ""Smoke alarm"", ""Fast w...",14000.0,t,30/03/23,04/01/23,20/03/23,f
544,544.0,6871835,2.02303E+13,36014559,1,1,19.39614,-99.17371,2,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Smoke alarm"", ""BBQ grill"", ""Pool"", ""TV with ...",31386.0,t,30/03/23,21/06/15,22/06/17,f
958,958.0,9946549,2.02303E+13,51117526,1,1,19.39196,-99.15615,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""Kitchen"", ""TV"", ""Essentials""]",17247.0,t,30/03/23,07/02/16,09/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23252,23250.0,8.29075E+17,2.02303E+13,104953556,5.3,6.2,19.40880555,-99.1778369,2.9,1.4,...,Entire home,Entire home/apt,4 baths,"[""Ethernet connection"", ""Pack \u2019n play/Tra...",13541.0,t,30/03/23,09/03/23,13/03/23,t
23470,23468.0,8.38378E+17,2.02303E+13,503547027,1,1,19.4092605,-99.1766356,2.9,1.4,...,Entire home,Entire home/apt,3 baths,"[""Stainless steel oven"", ""Ethernet connection""...",10711.0,t,30/03/23,05/03/23,09/03/23,t
23693,23691.0,8.43086E+17,2.02303E+13,8995867,17,18,19.41382,-99.17518,2.9,1.4,...,Entire home,Entire home/apt,5 baths,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",10371.0,t,30/03/23,20/03/23,27/03/23,t
24105,24103.0,8.53048E+17,2.02303E+13,10764020,5.3,6.2,19.4326408,-99.1972817,2.9,1.4,...,Entire serviced apartment,Entire home/apt,4 baths,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...",11038.0,t,30/03/23,24/03/23,24/03/23,t
24194,24192.0,8.56441E+17,2.02303E+13,114903513,2,3,19.40870079,-99.17367804,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Conditioner"", ""Long term stays allowed"", ""Wi...",17592.0,t,30/03/23,29/03/23,29/03/23,t

In [27]:
#Convertir DataFrame a CSV
filtro6.to_csv("Etapa2_filtrof_México.csv")

In [28]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrof_México.csv")

g) Los registros cuyo review_scores_cleanliness > 4.5

In [54]:
filtro7 = df[df['review_scores_cleanliness'] > 4.5]
filtro7

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
1,1.0,2072354,2.02303E+13,16840050,3,3,19.35358,-99.16948,2,1,...,Entire guest suite,Entire home/apt,1 bath,"[""Free street parking"", ""Cleaning products"", ""...",830.0,t,30/03/23,01/01/14,04/11/22,f
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
3,3.0,35797,2.02303E+13,153786,1,1,19.38283,-99.2,2,1,...,Entire villa,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24221,24219.0,8.53924E+17,2.02303E+13,488030249,3,4,19.39666335,-99.14814491,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",760.0,t,30/03/23,29/03/23,29/03/23,f
24222,24220.0,8.53967E+17,2.02303E+13,506816029,1,1,19.39202345,-99.11872158,7,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Lake access"", ""Ski-in/Ski-out"", ""Wifi"", ""Out...",1520.0,t,29/03/23,29/03/23,29/03/23,t
24223,24221.0,8.54225E+17,2.02303E+13,154670560,1,6,19.3710885,-99.1901864,2,2,...,Private room in home,Private room,2.5 shared baths,"[""Luggage dropoff allowed"", ""Shared patio or b...",533.0,t,29/03/23,29/03/23,29/03/23,f
24224,24222.0,8.54248E+17,2.02303E+13,7799414,13,13,19.4037919,-99.1649783,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Condit...",1200.0,t,30/03/23,29/03/23,29/03/23,t
24225,24223.0,8.5426E+17,2.02303E+13,506864314,2,2,19.42628282,-99.17560335,6,3,...,Entire rental unit,Entire home/apt,1 bath,"[""Long term stays allowed"", ""Cleaning products...",1720.0,t,30/03/23,29/03/23,29/03/23,t

In [30]:
#Convertir DataFrame a CSV
filtro7.to_csv("Etapa2_filtrog_México.csv")

In [31]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtrog_México.csv")

h) Los registros cuyo review_scores_value > 4.9

In [55]:
filtro8 = df[df['review_scores_value'] > 4.9]
filtro8

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
10,10.0,2083241,2.02303E+13,8282570,7,7,19.4153,-99.16763,3,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1881.0,t,30/03/23,03/10/14,13/03/23,f
11,11.0,67703,2.02303E+13,334451,3,5,19.41152,-99.16857,4,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Record player"", ""Extra pillows and blankets""...",2088.0,t,30/03/23,17/11/11,01/01/23,f
13,13.0,70644,2.02303E+13,212109,3,4,19.35448,-99.16217,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Luggag...",1097.0,t,29/03/23,14/02/12,31/01/23,f
24,24.0,783080,2.02303E+13,1767559,3,3,19.33009,-99.21418,1,1,...,Private room in home,Private room,1.5 baths,"[""Extra pillows and blankets"", ""Wifi"", ""Iron"",...",549.0,t,29/03/23,26/06/15,26/03/23,f
26,26.0,2118573,2.02303E+13,10802698,3,3,19.38777,-99.17532,6,3,...,Entire rental unit,Entire home/apt,3 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",2049.0,t,30/03/23,31/01/14,02/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24059,24057.0,8.52768E+17,2.02303E+13,10059555,2,2,19.42350255,-99.1653496,5,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Ethernet connection"", ""Smoke alarm"", ""BBQ gr...",1800.0,t,30/03/23,24/03/23,24/03/23,f
24060,24058.0,8.52783E+17,2.02303E+13,263823796,3,3,19.43405,-99.14772,4,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...",925.0,t,29/03/23,24/03/23,24/03/23,f
24111,24109.0,8.53066E+17,2.02303E+13,406773068,1,1,19.4077583,-99.1353001,3,2,...,Entire rental unit,Entire home/apt,1.5 baths,"[""Free street parking"", ""Conditioner"", ""Single...",750.0,t,29/03/23,26/03/23,26/03/23,f
24129,24127.0,8.53139E+17,2.02303E+13,257870736,1,2,19.41114268,-99.16315187,1,1,...,Private room in home,Private room,1.5 shared baths,"[""Wifi"", ""Paid parking on premises"", ""Washer"",...",250.0,t,30/03/23,26/03/23,26/03/23,t
24190,24188.0,8.56097E+17,2.02303E+13,484538652,12,12,19.41406964,-99.177642,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Co...",891.0,t,30/03/23,29/03/23,29/03/23,t

In [33]:
#Convertir DataFrame a CSV
filtro8.to_csv("Etapa2_filtroh_México.csv")

In [34]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroh_México.csv")

i) Los registros cuya availability_365<100

In [56]:
df['availability_365'].unique()

array(['324', '346', '87', '363', '357', '240', '144', '168', '156',
       '270', '153', '362', '358', '145', '340', '350', '284', '365',
       '317', '303', '88', '280', '341', '336', '304', '194', '295',
       '354', '328', '214', '356', '155', '197', '0', '26', '305', '348',
       '307', '269', '361', '313', '211', '332', '326', '272', '247',
       '127', '266', '330', '287', '334', '296', '188', '312', '167',
       '162', '288', '120', '179', '331', '253', '90', '114', '184',
       '364', '292', '344', '142', '207', '360', '80', '137', '2', '72',
       '30', '234', '298', '11', '121', '327', '333', '116', '48', '250',
       '84', '256', '318', '252', '347', '204', '329', '176', '209',
       '139', '16', '152', '335', '276', '200', '146', '62', '178', '81',
       '181', '238', '251', '159', '172', '325', '75', '337', '193',
       '134', '149', '355', '322', '248', '136', '174', '262', '51',
       '274', '302', '259', '74', '210', '222', '316', '58', '132', '71',
       '160', '50', '359', '183', '315', '180', '173', '123', '255',
       '343', '54', '221', '237', '57', '352', '203', '79', '258', '267',
       '56', '175', '297', '77', '49', '308', '208', '246', '345', '171',
       '89', '319', '286', '112', '189', '254', '201', '73', '263', '52',
       '265', '301', '236', '143', '323', '310', '15', '349', '17', '309',
       '199', '282', '85', '245', '321', '220', '110', '37', '125', '106',
       '353', '278', '61', '273', '283', '198', '339', '83', '63', '299',
       '291', '289', '342', '32', '141', '148', '161', '351', '150', '3',
       '1', '165', '151', '320', '33', '212', '118', '135', '241', '8',
       '70', '213', '6', '103', '177', '228', '166', '300', '186', '40',
       '126', '242', '314', '39', '23', '158', '154', '202', '53', '268',
       '281', '271', '18', '277', '27', '86', '244', '55', '82', '14',
       '20', '43', '25', '216', '275', '99', '338', '131', '60', '133',
       '311', '285', '130', '230', '163', '47', '44', '46', '147', '66',
       '279', '294', '233', '164', '105', '65', '243', '169', '217', '35',
       '69', '59', '76', '124', '196', '306', '122', '235', '117', '187',
       '239', '78', '190', '192', '128', '93', '293', '34', '28', '191',
       '229', '64', '41', '5', '261', '206', '67', '19', '92', '170',
       '10', '104', '115', '98', '232', '31', '224', '157', '9', '260',
       '94', '227', '45', '138', '13', '24', '22', '182', '257', '226',
       '21', '29', '264', '225', '36', '113', '91', '119', '290', '42',
       '38', '12', '249', '101', '223', '140', '195', '4', '231', '218',
       '97', '185', '96', '102', '7', '215', '68', '129', '109', '205',
       '107', '100', '111', '108', '219', 'f', '95'], dtype=object)

In [59]:
df.availability_365 = df.availability_365.astype(int)

In [58]:
#Se sustituye con cero, ya que no se sabe cual era el valor real del dato. 
df.availability_365 = df.availability_365.replace({'f':'0'}, regex=False)

In [60]:
filtro9=df[df['availability_365'] < 100]
filtro9

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
21,21.0,131610,2.02303E+13,647454,3,4,19.35416,-99.16488,2,1,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,29/03/23,06/09/14,29/01/23,f
26,26.0,2118573,2.02303E+13,10802698,3,3,19.38777,-99.17532,6,3,...,Entire rental unit,Entire home/apt,3 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",2049.0,t,30/03/23,31/01/14,02/03/23,f
37,37.0,187030,2.02303E+13,899360,6,8,19.41057,-99.1773,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",50000.0,t,30/03/23,01/11/11,15/03/23,f
38,38.0,187745,2.02303E+13,899360,6,8,19.41057,-99.1773,3,1,...,Entire loft,Entire home/apt,2 baths,"[""Wifi"", ""Washer"", ""Free street parking"", ""Hos...",5000.0,t,30/03/23,10/11/13,03/01/18,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24161,24159.0,8.55707E+17,2.02303E+13,3394561,2,6,19.42935324,-99.14764203,2,1,...,Private room in rental unit,Private room,1 shared bath,"[""Free street parking"", ""Hot water kettle"", ""L...",444.0,t,29/03/23,26/03/23,26/03/23,t
24167,24165.0,8.57303E+17,2.02303E+13,227002676,5.3,6.2,19.42598815,-99.17524549,4,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Single level home"", ""Long term stays allowed...",3001.0,t,30/03/23,26/03/23,26/03/23,t
24172,24170.0,8.57303E+17,2.02303E+13,227002676,5.3,6.2,19.42401497,-99.1743961,4,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Single level home"", ""Long term stays allowed...",3001.0,t,30/03/23,26/03/23,26/03/23,t
24188,24186.0,8.56096E+17,2.02303E+13,2086889,1,1,19.411379,-99.17127225,5,2,...,Entire rental unit,Entire home/apt,2.5 baths,"[""Stainless steel oven"", ""Smoke alarm"", ""55\"" ...",1477.0,t,30/03/23,26/03/23,26/03/23,f
24195,24193.0,8.56446E+17,2.02303E+13,3240358,3,3,19.41337044,-99.17344659,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Washer"", ""BBQ grill"",...",2130.0,t,30/03/23,29/03/23,29/03/23,f

In [41]:
#Convertir DataFrame a CSV
filtro9.to_csv("Etapa2_filtroi_México.csv")

In [42]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroi_México.csv")

j) Los registros cuya host_ response_time sea "within an hour"

In [61]:
filtro10 = df[df["host_response_time"] == "within an hour"]
filtro10

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
3,3.0,35797,2.02303E+13,153786,1,1,19.38283,-99.2,2,1,...,Entire villa,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
6,6.0,56074,2.02303E+13,265650,2,6,19.43977,-99.15605,2,1,...,Entire condo,Entire home/apt,1 bath,"[""Luggage dropoff allowed"", ""Long term stays a...",650.0,t,29/03/23,02/04/11,21/01/23,f
7,7.0,61792,2.02303E+13,299558,2,3,19.41083,-99.18057,2,1,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,30/03/23,01/11/17,31/12/22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24221,24219.0,8.53924E+17,2.02303E+13,488030249,3,4,19.39666335,-99.14814491,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",760.0,t,30/03/23,29/03/23,29/03/23,f
24222,24220.0,8.53967E+17,2.02303E+13,506816029,1,1,19.39202345,-99.11872158,7,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Lake access"", ""Ski-in/Ski-out"", ""Wifi"", ""Out...",1520.0,t,29/03/23,29/03/23,29/03/23,t
24223,24221.0,8.54225E+17,2.02303E+13,154670560,1,6,19.3710885,-99.1901864,2,2,...,Private room in home,Private room,2.5 shared baths,"[""Luggage dropoff allowed"", ""Shared patio or b...",533.0,t,29/03/23,29/03/23,29/03/23,f
24224,24222.0,8.54248E+17,2.02303E+13,7799414,13,13,19.4037919,-99.1649783,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Condit...",1200.0,t,30/03/23,29/03/23,29/03/23,t
24225,24223.0,8.5426E+17,2.02303E+13,506864314,2,2,19.42628282,-99.17560335,6,3,...,Entire rental unit,Entire home/apt,1 bath,"[""Long term stays allowed"", ""Cleaning products...",1720.0,t,30/03/23,29/03/23,29/03/23,t

In [44]:
#Convertir DataFrame a CSV
filtro10.to_csv("Etapa2_filtroj_México.csv")

In [45]:
#descargar archivo filtrado en csv
from google.colab import files 
files.download("Etapa2_filtroj_México.csv")